version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@02.2.1

jobs:
  update-service:
    docker:
      - image: "cimg/python:3.9.1"
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${SERVICE_NAME},tag=latest"
          family: ${TASK_DEF_NAME}
          service-name: ${SERVICE_NAME}
          skip-task-definition-registration: true
          force-new-deployment: true

  update-service-prd:
    docker:
      - image: "cimg/python:3.9.1"
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${SERVICE_NAME},tag=prd"
          family: prd_${SERVICE_NAME}
          service-name: ${SERVICE_NAME}
          skip-task-definition-registration: true
          force-new-deployment: true

  update-service-production:
    docker:
      - image: "cimg/python:3.9.1"
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${SERVICE_NAME},tag=prd"
          family: production_${SERVICE_NAME}
          service-name: ${SERVICE_NAME}
          skip-task-definition-registration: true
          force-new-deployment: true

  update-service-uat:
    docker:
      - image: "cimg/python:3.9.1"
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${SERVICE_NAME},tag=uat"
          family: uat_${SERVICE_NAME}
          service-name: ${SERVICE_NAME}
          skip-task-definition-registration: true
          force-new-deployment: true

  update-service-staging-us-west-1:
    docker:
      - image: "cimg/python:3.9.1"
    steps:
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${SERVICE_NAME},tag=prd"
          family: staging_${SERVICE_NAME}
          service-name: ${SERVICE_NAME}
          skip-task-definition-registration: true
          force-new-deployment: true

workflows:
  deploy-prod-us-east-1:
    when:
      and:
        - and: [<< pipeline.parameters.GHA_Action >>]
        - equal: ["deploy-prod-us-east-1", << pipeline.parameters.GHA_Action >>]
    jobs:
      - update-service-production:
          context:
            - hopstack-prd-us-east-1

  deploy-prod-ap-southeast-1:
    when:
      and:
        - and: [<< pipeline.parameters.GHA_Action >>]
        - equal: ["deploy-prod-us-east-1", << pipeline.parameters.GHA_Action >>]
    jobs:
      - update-service-production:
          context:
            - hopstack-prd-ap-southeast-1

  deploy-prod-eu-west-2:
    when:
      and:
        - and: [ << pipeline.parameters.GHA_Action >> ]
        - equal: [ "deploy-prod-eu-west-2", << pipeline.parameters.GHA_Action >> ]
    jobs:
      - update-service-production:
          context:
            - hopstack-prd-eu-west-2

  deploy-stg-us-west-1:
    when:
      and:
        - and: [ << pipeline.parameters.GHA_Action >> ]
        - equal: [ "deploy-stg-us-west-1", << pipeline.parameters.GHA_Action >> ]
    jobs:
      - update-service-staging-us-west-1:
          context:
            - hopstack-stg-us-west-1

  deploy-uat-ap-southeast-1:
    when:
      and:
        - and: [<< pipeline.parameters.GHA_Action >>]
        - equal:
            ["deploy-uat-ap-southeast-1", << pipeline.parameters.GHA_Action >>]
    jobs:
      - update-service-uat:
          context:
            - hopstack-uat-ap-southeast-1
